---
- name: Use the create_file_role
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: create_file_role
      vars:
        create_file_path: "/tmp/from_role_playbook.txt"
        create_file_content: "Content set directly in playbook vars."
